version: "3"
services:
  mysql:
    image: mysql:8.0.13
    ports:
      - 4306:3306
      - 43060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: feedback
    volumes:
      - ./../../workdir/mysql:/var/lib/mysql
